[2019-10-09 06:06:01,177] {{models.py:1361}} INFO - Dependencies all met for <TaskInstance: housing_price_prediction_testing.pull_predicted_labels 2019-10-09T05:58:05.761589+00:00 [queued]>
[2019-10-09 06:06:01,218] {{models.py:1361}} INFO - Dependencies all met for <TaskInstance: housing_price_prediction_testing.pull_predicted_labels 2019-10-09T05:58:05.761589+00:00 [queued]>
[2019-10-09 06:06:01,218] {{models.py:1573}} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-10-09 06:06:01,266] {{models.py:1595}} INFO - Executing <Task(PythonOperator): pull_predicted_labels> on 2019-10-09T05:58:05.761589+00:00
[2019-10-09 06:06:01,266] {{base_task_runner.py:118}} INFO - Running: ['bash', '-c', 'airflow run housing_price_prediction_testing pull_predicted_labels 2019-10-09T05:58:05.761589+00:00 --job_id 30 --raw -sd DAGS_FOLDER/housing_price_prediction_testing.py --cfg_path /tmp/tmpb6s_zwbz']
[2019-10-09 06:06:01,907] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels [2019-10-09 06:06:01,907] {{settings.py:174}} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
[2019-10-09 06:06:02,480] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels [2019-10-09 06:06:02,478] {{__init__.py:51}} INFO - Using executor LocalExecutor
[2019-10-09 06:06:03,015] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels [2019-10-09 06:06:03,014] {{models.py:271}} INFO - Filling up the DagBag from /usr/local/airflow/dags/housing_price_prediction_testing.py
[2019-10-09 06:06:03,060] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels [2019-10-09 06:06:03,060] {{cli.py:484}} INFO - Running <TaskInstance: housing_price_prediction_testing.pull_predicted_labels 2019-10-09T05:58:05.761589+00:00 [running]> on host 63734ffeb1b4
[2019-10-09 06:06:03,109] {{models.py:1760}} ERROR - name 'response' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 95, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 100, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/housing_price_prediction_testing.py", line 50, in pull_predicted_labels
    response_dict=ast.literal_eval(ast.literal_eval(response)['1:Fetch Housing Price Prediction Outputs']['message'])
NameError: name 'response' is not defined
[2019-10-09 06:06:03,113] {{models.py:1783}} INFO - Marking task as UP_FOR_RETRY
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels Traceback (most recent call last):
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     args.func(args)
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     return f(*args, **kwargs)
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 490, in run
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     _run(args, dag, ti)
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 406, in _run
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     pool=args.pool,
[2019-10-09 06:06:03,162] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     return func(*args, **kwargs)
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     result = task_copy.execute(context=context)
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 95, in execute
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     return_value = self.execute_callable()
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 100, in execute_callable
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     return self.python_callable(*self.op_args, **self.op_kwargs)
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels   File "/usr/local/airflow/dags/housing_price_prediction_testing.py", line 50, in pull_predicted_labels
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels     response_dict=ast.literal_eval(ast.literal_eval(response)['1:Fetch Housing Price Prediction Outputs']['message'])
[2019-10-09 06:06:03,163] {{base_task_runner.py:101}} INFO - Job 30: Subtask pull_predicted_labels NameError: name 'response' is not defined
[2019-10-09 06:06:06,275] {{logging_mixin.py:95}} INFO - [2019-10-09 06:06:06,274] {{jobs.py:2627}} INFO - Task exited with return code 1
